# Run from the repo root:  Rscript R/test_golden.R   (compares the base-R scorer with the ORIGINAL CellTypist decision values)
source("R/progenitor_score.R")
m <- bmps_read_model("src/progenitor_score/models/bone_marrow_zeng2025_v1")
X <- as.matrix(read.csv(gzfile("tests/golden_X.csv.gz"), row.names = 1, check.names = FALSE))
F <- as.matrix(read.csv(gzfile("tests/golden_decision_full.csv.gz"), row.names = 1, check.names = FALSE))
M <- as.matrix(read.csv(gzfile("tests/golden_decision_missing.csv.gz"), row.names = 1, check.names = FALSE))
drop <- readLines("tests/golden_dropped_genes.txt")
D <- bmps_decision(X, colnames(X), m); keep <- !(colnames(X) %in% drop); D2 <- bmps_decision(X[, keep], colnames(X)[keep], m)
d1 <- max(abs(D - F)); d2 <- max(abs(D2 - M)); same <- all(apply(D, 1, which.max) == apply(F, 1, which.max))
cat(sprintf("max abs diff full: %.2e | missing genes: %.2e | same best state: %s\n", d1, d2, same))
stopifnot(d1 < 1e-2, d2 < 1e-2, same)
calls <- bmps_calls(D, m); stopifnot(all(calls$bm_state == colnames(F)[apply(F, 1, which.max)]))
cat("R scorer matches the original CellTypist model\n")
